// <auto-generated />
using DemoMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("DemoMVC.Models.Entities.Student", b =>
                {
                    b.Property<string>("Ho_Ten")
                        .HasColumnType("TEXT");

                    b.Property<string>("Student_Id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Ho_Ten");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
